import Head from "next/head"
import "../styles/globals.css"
import type { AppProps } from "next/app"
import ym, { YMInitializer } from "react-yandex-metrika"

export default function App({
  Component,
  pageProps,
  router,
}: AppProps): React.JSX.Element {
  // При каждом изменении роута, будем отправлять в Yandex Metrika событие, что мы успешно перешли
  router.events.on("routeChangeComplete", (url: string) => {
    if (typeof window !== "undefined") {
      ym("hit", url)
    }
  })

  return (
    <>
      <Head>
        <title>App component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          property="og:url"
          content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath}
        />
        <meta property="og:locale" content="ru_RU" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="preconnect" href="https://mc.yandex.ru" />

        <style
          dangerouslySetInnerHTML={{
            __html: `</style>
    <link
      rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap"
      media="print"
      onload="this.media='all';"
    />
    <style>`,
          }}
        ></style>
      </Head>
      <YMInitializer
        accounts={[]}
        options={{ webvisor: true, defer: true }}
        version="2"
      />

      <Component {...pageProps} />
    </>
  )
}
