import Head from "next/head"
import "../styles/globals.css"
import type { AppProps } from "next/app"

export default function App({
  Component,
  pageProps,
}: AppProps): React.JSX.Element {
  return (
    <>
      <Head>
        <title>App component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        {/* TODO: посмотреть правильно ли я все сделал и посмотреть что значит media="print и onload=..." */}
        {/* <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap"
        /> */}
        <style
          dangerouslySetInnerHTML={{
            __html: `</style>
    <link
      rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap"
      media="print"
      onload="this.media='all';"
    />
    <style>`,
          }}
        ></style>
      </Head>
      <Component {...pageProps} />
    </>
  )
}
